spring:
  application:
    name: kubki
  # H2 - zamień na Mongo jak będzie czas
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
    ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb

server:
  port: 8888